<Project><PropertyGroup><Version>0.1.2-beta.14</Version><AssemblyVersion>0.1.2.14</AssemblyVersion><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><Deterministic>true</Deterministic><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile></PropertyGroup></Project>
