<Project><PropertyGroup><Version>0.1.2-beta.13</Version><AssemblyVersion>0.1.2.13</AssemblyVersion><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><Deterministic>true</Deterministic><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile></PropertyGroup></Project>
