import {chromium} from '@playwright/test';
import fs from 'node:fs';
const browser=await chromium.launch();
const errors=[];
const page=await browser.newPage({viewport:{width:1440,height:940}});
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:18473');
await page.getByRole('button',{name:'浏览界面预览'}).click();
await page.screenshot({path:'../.local/lobby.png',animations:'disabled'});
await page.getByRole('button',{name:/03.*肉丸工艺/}).click();
await page.screenshot({path:'../.local/detail.png',animations:'disabled'});
await page.getByRole('button',{name:'宿迁三网',exact:false}).click();
await page.getByRole('button',{name:'关闭错误'}).click();
await page.getByRole('button',{name:'启动器设置'}).click();
await page.getByRole('button',{name:'外观',exact:true}).click();
await page.getByRole('switch').click();
await page.screenshot({path:'../.local/settings.png',animations:'disabled'});
await page.setViewportSize({width:900,height:700});
await page.getByRole('button',{name:'游戏大厅',exact:false}).click();
await page.screenshot({path:'../.local/lobby-900.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Horizontal overflow at 900px');
fs.writeFileSync('../.local/ui-check.json',JSON.stringify({errors,viewportChecks:[1440,900],reducedMotion:true},null,2));
if(errors.length)throw new Error(errors.join('\n'));
await browser.close();
