import {chromium,expect} from '@playwright/test';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true});
const errors=[];
const page=await browser.newPage({viewport:{width:1440,height:940}});
page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.LAUNCHER_UI_URL || 'http://127.0.0.1:18473');
await page.getByRole('button',{name:'浏览界面预览'}).click();
for(const [width,height] of [[1440,940],[1280,820],[1024,768]]){
 await page.setViewportSize({width,height});
 const cards=page.locator('.world-card');
 await expect(cards).toHaveCount(4);
 await expect(page.locator('.sidebar .nav-item').filter({hasText:'游戏大厅'}).locator('span')).toHaveText('04');
 const boxes=await cards.evaluateAll(nodes=>nodes.map(node=>{
  const box=node.getBoundingClientRect();return {x:box.x,y:box.y,bottom:box.bottom,width:box.width};
 }));
 expect(boxes[0].y).toBe(boxes[1].y);
 expect(boxes[2].y).toBe(boxes[3].y);
 expect(boxes[0].x).toBe(boxes[2].x);
 expect(boxes[1].x).toBe(boxes[3].x);
 expect(boxes[2].y).toBeGreaterThan(boxes[0].y);
 expect(Math.max(...boxes.map(box=>box.bottom))).toBeLessThanOrEqual(height);
 const overflow=await cards.evaluateAll(nodes=>nodes.flatMap(card=>[...card.querySelectorAll('h2,.tags,.card-route,.card-bottom')]).some(node=>node.scrollWidth>node.clientWidth+1));
 expect(overflow).toBe(false);
}
await page.setViewportSize({width:1280,height:820});
await page.screenshot({path:'../.local/vw-lobby-final.png',animations:'disabled'});
await page.locator('.world-card').filter({hasText:'虚空行者'}).click();
await expect(page.locator('.detail h1')).toHaveText('虚空行者');
await expect(page.locator('.routes .route')).toHaveCount(2);
await expect(page.locator('.routes .route').nth(0)).toContainText('河北阿里云');
await expect(page.locator('.routes .route').nth(1)).toContainText('宿迁三网');
await expect(page.locator('.launch-panel')).toContainText('Java 8 x64');
await expect(page.locator('.launch-panel')).toContainText('4 GiB');
const routes=await page.locator('.routes .route').evaluateAll(nodes=>nodes.map(node=>({width:node.getBoundingClientRect().width,y:node.getBoundingClientRect().y,overflow:node.scrollWidth>node.clientWidth+1})));
expect(routes[0].width).toBe(routes[1].width);
expect(routes[0].y).toBe(routes[1].y);
expect(routes.some(route=>route.overflow)).toBe(false);
await page.screenshot({path:'../.local/vw-detail-final.png',animations:'disabled'});
await page.getByRole('button',{name:'所有世界'}).click();
await page.setViewportSize({width:1440,height:940});
await page.screenshot({path:'../.local/lobby.png',animations:'disabled'});
await page.locator('.world-card').filter({hasText:'肉丸工艺'}).click();
await page.screenshot({path:'../.local/detail.png',animations:'disabled'});
await page.getByRole('button',{name:'宿迁三网',exact:false}).click();
await page.getByRole('button',{name:'关闭错误'}).click();
await page.getByRole('button',{name:'启动器设置'}).click();
await page.getByRole('button',{name:'外观',exact:true}).click();
await page.getByRole('switch').click();
await page.screenshot({path:'../.local/settings.png',animations:'disabled'});
await page.setViewportSize({width:900,height:700});
await page.getByRole('button',{name:'游戏大厅',exact:false}).click();
await page.screenshot({path:'../.local/lobby-900.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Horizontal overflow at 900px');
fs.writeFileSync('../.local/ui-check.json',JSON.stringify({errors,viewportChecks:[1440,1280,1024,900],fourWorldDesktopGrid:'2x2',sidebarCount:'04',equalVwRoutes:true,reducedMotion:true},null,2));
if(errors.length)throw new Error(errors.join('\n'));
await browser.close();
